CREATE TABLE ADMINS (
    ADMINID INT IDENTITY(1, 1) PRIMARY KEY,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL
);

CREATE TABLE CATALOGUE (
    CATALOGUEID INT IDENTITY(3001, 1) PRIMARY KEY,
    PROJECTNAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    ESTIMATEDCOST DECIMAL(10, 2) NOT NULL,
    IMAGEURL VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENTS (
    CLIENTID INT IDENTITY(1001, 1) PRIMARY KEY,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL
);

CREATE TABLE RESERVATIONS (
    RESERVATIONID INT IDENTITY(7001, 1) PRIMARY KEY,
    CLIENTID INT,
    CATALOGUEID INT,
    RESERVATIONDATE DATE NOT NULL,
    FOREIGN KEY (CLIENTID) REFERENCES CLIENTS (CLIENTID),
    FOREIGN KEY (CATALOGUEID) REFERENCES CATALOGUE (CATALOGUEID)
);

CREATE TABLE INPROGRESSION (
    PROJECTID INT IDENTITY(6001, 1) PRIMARY KEY,
    ADMINID INT,
    RESERVATIONID INT,
    STARTDATE DATE NOT NULL,
    ENDDATE DATE,
    FOREIGN KEY (ADMINID) REFERENCES ADMINS (ADMINID),
    FOREIGN KEY (RESERVATIONID) REFERENCES RESERVATIONS (RESERVATIONID)
);

CREATE TABLE PROJECTARCHIVE (
    ARCHIVEID INT IDENTITY(8001, 1) PRIMARY KEY,
    PROJECTID INT,
    COMPLETIONDATE DATE NOT NULL,
    REVIEW VARCHAR(255),
    FOREIGN KEY (PROJECTID) REFERENCES INPROGRESSION (PROJECTID)
);

CREATE TABLE MATERIALINVENTORY (
    MATERIALID INT IDENTITY(2001, 1) PRIMARY KEY,
    MATERIALNAME VARCHAR(255) NOT NULL,
    BULKAMOUNT INT NOT NULL
);

CREATE TABLE VENDORS (
    VENDORID INT IDENTITY(4001, 1) PRIMARY KEY,
    VENDORNAME VARCHAR(255) NOT NULL,
    CONTACTPERSON VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE EMPLOYEEROSTER (
    EMPLOYEEID INT IDENTITY(5001, 1) PRIMARY KEY,
    ADMINID INT,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    POSITION VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    FOREIGN KEY (ADMINID) REFERENCES ADMINS (ADMINID)
);

CREATE TABLE APPOINTMENTS (
    APPOINTMENTID INT IDENTITY(9001, 1) PRIMARY KEY,
    CLIENTID INT,
    EMPLOYEEID INT,
    APPOINTMENTDATE DATE NOT NULL,
    APPOINTMENTTIME TIME NOT NULL,
    FOREIGN KEY (CLIENTID) REFERENCES CLIENTS (CLIENTID),
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEEROSTER (EMPLOYEEID)
);

CREATE TABLE FINANCIALTRANSACTIONS (
    TRANSACTIONID INT IDENTITY(0201, 1) PRIMARY KEY,
    ADMINID INT,
    TRANSACTIONDATE DATE NOT NULL,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    FOREIGN KEY (ADMINID) REFERENCES ADMINS (ADMINID)
);

CREATE TABLE MATERIALTRANSACTION (
    TRANSACTIONID INT PRIMARY KEY,
    MATERIALID INT,
    QUANTITY INT NOT NULL,
    VENDORID INT,
    FOREIGN KEY (TRANSACTIONID) REFERENCES FINANCIALTRANSACTIONS (TRANSACTIONID),
    FOREIGN KEY (MATERIALID) REFERENCES MATERIALINVENTORY (MATERIALID),
    FOREIGN KEY (VENDORID) REFERENCES VENDORS (VENDORID)
);

CREATE TABLE RESERVATIONTRANSACTION (
    TRANSACTIONID INT PRIMARY KEY,
    RESERVATIONID INT,
    FOREIGN KEY (TRANSACTIONID) REFERENCES FINANCIALTRANSACTIONS (TRANSACTIONID),
    FOREIGN KEY (RESERVATIONID) REFERENCES RESERVATIONS (RESERVATIONID)
);

CREATE TABLE SALARYTRANSACTION (
    TRANSACTIONID INT PRIMARY KEY,
    EMPLOYEEID INT,
    FOREIGN KEY (TRANSACTIONID) REFERENCES FINANCIALTRANSACTIONS (TRANSACTIONID),
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEEROSTER (EMPLOYEEID)
);

CREATE TABLE INSTALLMENTTRANSACTION (
    TRANSACTIONID INT PRIMARY KEY,
    INSTALLMENTNUM INT NOT NULL,
    PROJECTID INT,
    FOREIGN KEY (TRANSACTIONID) REFERENCES FINANCIALTRANSACTIONS (TRANSACTIONID),
    FOREIGN KEY (PROJECTID) REFERENCES INPROGRESSION (PROJECTID)
);

BACKUP DATABASE [DECORATEMYNEST] TO DISK = N'D:\zZz\Personal\University\3.1\Code\DecorateMyNest\DecorateMyNest_backup.bak' WITH NOFORMAT, NOINIT, NAME = N'DecorateMYNest-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, STATS = 10;