/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DecorateMyNest;

import java.sql.Date;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Musaddique Ali
 */
public class AppointmentsViewPanel extends javax.swing.JPanel {
        DefaultTableModel model = new DefaultTableModel();

        /**
         * Creates new form AdminViewPanel
         */
        public AppointmentsViewPanel() {
                initComponents();
                setRecordsToTable();
        }

        private void setRecordsToTable() {
                try {
                        Welcome.jdbc.preparedStatement = Welcome.jdbc.connection
                                        .prepareStatement("SELECT * FROM Appointments;");
                        Welcome.jdbc.resultSet = Welcome.jdbc.preparedStatement.executeQuery();
                        model = (DefaultTableModel) appointmentsTable.getModel();
                        model.setRowCount(0);
                        while (Welcome.jdbc.resultSet.next()) {
                                int appointmentID = Welcome.jdbc.resultSet.getInt("AppointmentID");
                                int clientID = Welcome.jdbc.resultSet.getInt("ClientID");
                                int employeeID = Welcome.jdbc.resultSet.getInt("EmployeeID");
                                Date appointmentDate = Welcome.jdbc.resultSet.getDate("AppointmentDate");
                                Time appointmentTime = Welcome.jdbc.resultSet.getTime("AppointmentTime");

                                model.addRow(new Object[] { appointmentID, clientID, employeeID, appointmentDate,
                                                appointmentTime });
                        }
                        appointmentsTable.setModel(model);
                } catch (SQLException ex) {
                        System.out.println(ex);
                }
                List<String> columnNamesList = Welcome.jdbc.getColumns("Appointments");

                jComboBoxselectcolumn.removeAllItems();

                DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
                for (String columnName : columnNamesList) {
                        comboBoxModel.addElement(columnName);
                }

                jComboBoxselectcolumn.setModel(comboBoxModel);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jComboBoxselectcolumn = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        okbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentsTable = new javax.swing.JTable();
        searchbylabel = new javax.swing.JLabel();
        dltbtn = new javax.swing.JButton();

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 255, 255));

        jComboBoxselectcolumn.setBackground(new java.awt.Color(255, 255, 250));
        jComboBoxselectcolumn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxselectcolumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setBackground(new java.awt.Color(255, 255, 250));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        okbtn.setBackground(new java.awt.Color(255, 255, 250));
        okbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        okbtn.setText("OK");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });

        appointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AppointmentID", "ClientID", "EmployeeID", "AppointmentDate", "AppointmentTime"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(appointmentsTable);

        searchbylabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        searchbylabel.setText("Search By");

        dltbtn.setBackground(new java.awt.Color(255, 255, 250));
        dltbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dltbtn.setText("Delete");
        dltbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(searchbylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jComboBoxselectcolumn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266)
                        .addComponent(okbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dltbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxselectcolumn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(dltbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okbtnActionPerformed
                String selectedColumn = (String) jComboBoxselectcolumn.getSelectedItem();
                String searchTerm = jTextField1.getText();

                try {
                        String query = "SELECT * FROM Appointments WHERE " + selectedColumn + " LIKE ?";
                        Welcome.jdbc.preparedStatement = Welcome.jdbc.connection.prepareStatement(query);
                        Welcome.jdbc.preparedStatement.setString(1, "%" + searchTerm + "%");

                        Welcome.jdbc.resultSet = Welcome.jdbc.preparedStatement.executeQuery();
                        model.setRowCount(0); // Clear existing data

                        while (Welcome.jdbc.resultSet.next()) {
                                int appointmentID = Welcome.jdbc.resultSet.getInt("AppointmentID");
                                int clientID = Welcome.jdbc.resultSet.getInt("ClientID");
                                int employeeID = Welcome.jdbc.resultSet.getInt("EmployeeID");
                                Date appointmentDate = Welcome.jdbc.resultSet.getDate("AppointmentDate");
                                Time appointmentTime = Welcome.jdbc.resultSet.getTime("AppointmentTime");

                                model.addRow(new Object[] { appointmentID, clientID, employeeID, appointmentDate,
                                                appointmentTime });
                        }

                        // Update the table model with search results
                        appointmentsTable.setModel(model);
                } catch (SQLException ex) {
                        System.out.println(ex);
                }
        }// GEN-LAST:event_okbtnActionPerformed

        private void dltbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dltbtnActionPerformed
                // TODO add your handling code here:
                {
                        int selectedRowIndex = appointmentsTable.getSelectedRow();

                        if (selectedRowIndex == -1) {
                                JOptionPane.showMessageDialog(this, "Please select a row to delete.");
                                return;
                        }

                        int id = (int) appointmentsTable.getValueAt(selectedRowIndex, 0);

                        int rowsAffected = Welcome.jdbc.deleteData("Appointments", id, "appointmentID");

                        if (rowsAffected > 0) {
                                JOptionPane.showMessageDialog(this, "Row deleted successfully.");

                                DefaultTableModel model = (DefaultTableModel) appointmentsTable.getModel();
                                model.removeRow(selectedRowIndex);
                        } else {
                                JOptionPane.showMessageDialog(this, "Error deleting row.");
                        }
                }

        }// GEN-LAST:event_dltbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appointmentsTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton dltbtn;
    private javax.swing.JComboBox<String> jComboBoxselectcolumn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton okbtn;
    private javax.swing.JLabel searchbylabel;
    // End of variables declaration//GEN-END:variables
}
