/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DecorateMyNest;

import java.awt.Dialog;
import java.sql.Time;
import java.sql.Date;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Musaddique Ali
 */
public class AppointmentsEditPanel extends javax.swing.JPanel {

        /**
         * Creates new form AdminViewPanel
         */
        public AppointmentsEditPanel() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        fnamelabel = new javax.swing.JLabel();
        clientID = new javax.swing.JTextField();
        lnamelabel = new javax.swing.JLabel();
        employeeID = new javax.swing.JTextField();
        phonelabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        insertbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Year = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        Month = new javax.swing.JTextField();
        Hour = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Minute = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        selectClient = new javax.swing.JButton();
        selectEmployee = new javax.swing.JButton();

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 153, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 51));

        fnamelabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        fnamelabel.setText("Client ID");

        clientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clientID.setForeground(new java.awt.Color(255, 255, 255));
        clientID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lnamelabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lnamelabel.setText("Employee ID");

        employeeID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        employeeID.setForeground(new java.awt.Color(255, 255, 255));
        employeeID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        phonelabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        phonelabel.setText("Appoinment Time");

        emaillabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        emaillabel.setText("Appoinment Date");

        insertbtn.setBackground(new java.awt.Color(255, 249, 242));
        insertbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertbtn.setText("Insert");
        insertbtn.setAlignmentY(9.0F);
        insertbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        insertbtn.setIconTextGap(6);
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(255, 249, 242));
        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.setAlignmentY(9.0F);
        updatebtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        updatebtn.setIconTextGap(6);
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(255, 249, 242));
        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.setAlignmentY(9.0F);
        clearbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        clearbtn.setIconTextGap(6);
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setText("/");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setText("/");

        Year.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Year.setForeground(new java.awt.Color(255, 255, 255));
        Year.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        Month.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Month.setForeground(new java.awt.Color(255, 255, 255));
        Month.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Hour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Hour.setForeground(new java.awt.Color(255, 255, 255));
        Hour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Hour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HourActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setText(":");

        Minute.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Minute.setForeground(new java.awt.Color(255, 255, 255));
        Minute.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jRadioButton1.setText("AM");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jRadioButton2.setText("PM");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        selectClient.setBackground(new java.awt.Color(255, 249, 242));
        selectClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selectClient.setText("Select");
        selectClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        selectClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectClientActionPerformed(evt);
            }
        });

        selectEmployee.setBackground(new java.awt.Color(255, 249, 242));
        selectEmployee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selectEmployee.setText("Select");
        selectEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        selectEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emaillabel, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                            .addComponent(phonelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clientID)
                            .addComponent(employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(Hour, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(Minute, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jRadioButton2)))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectClient, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1044, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(fnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(phonelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectClient, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(Hour, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Minute, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)))))
                .addGap(158, 158, 158)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectClientActionPerformed
        // TODO add your handling code here:
        JDialog selectDialog = new JDialog(new JFrame(), "Select Client ID", Dialog.ModalityType.APPLICATION_MODAL);
        selectDialog.add(new SelectClient());
        selectDialog.setSize(1230, 850);
        selectDialog.setVisible(true);
        clientID.setText(Welcome.jdbc.clientID+"");
        Welcome.jdbc.clientID=-1;
    }//GEN-LAST:event_selectClientActionPerformed

    private void selectEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectEmployeeActionPerformed
        // TODO add your handling code here:
        JDialog selectDialog = new JDialog(new JFrame(), "Select Employee ID", Dialog.ModalityType.APPLICATION_MODAL);
        selectDialog.add(new SelectEmployee());
        selectDialog.setSize(1230, 850);
        selectDialog.setVisible(true);
        employeeID.setText(Welcome.jdbc.employeeRosterID+"");
        Welcome.jdbc.employeeRosterID=-1;
    }//GEN-LAST:event_selectEmployeeActionPerformed

        private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearbtnActionPerformed
                // TODO add your handling code here:
                clientID.setText("");
                employeeID.setText("");
                Date.setText("");
                Month.setText("");
                Year.setText("");
                Hour.setText("");
                Minute.setText("");
                jRadioButton1.setSelected(true);
                jRadioButton2.setSelected(false);

        }// GEN-LAST:event_clearbtnActionPerformed

        private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_insertbtnActionPerformed
                if (clientID.getText().equals("") || employeeID.getText().equals("") || Date.getText().equals("")
                                || Month.getText().equals("") || Year.getText().equals("") || Hour.getText().equals("")
                                || Minute.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Please Fill-up all fields");
                        return;
                }
                try {
                        int hour = 0;
                        if (jRadioButton1.isSelected()) {
                                hour = Integer.parseInt(Hour.getText());
                        }
                        if (jRadioButton2.isSelected()) {
                                hour = Integer.parseInt(Hour.getText()) + 12;
                        }
                        System.out.println(Year.getText()+Month.getText()+Date.getText());
                        Welcome.jdbc.appointmentsInsert(Integer.parseInt(clientID.getText()),
                                        Integer.parseInt(employeeID.getText()),
                                        new Date(Integer.parseInt(Year.getText())-1900,Integer.parseInt(Month.getText())-1,
                                                        Integer.parseInt(Date.getText())),
                                        new Time(hour, Integer.parseInt(Minute.getText()), 0));
                        JOptionPane.showMessageDialog(this, "Inserted Successfully");
                        // Clear your input fields related to Appointments here
                        clientID.setText("");
                        employeeID.setText("");
                        Date.setText("");
                        Month.setText("");
                        Year.setText("");
                        Hour.setText("");
                        Minute.setText("");
                        jRadioButton1.setSelected(true);
                        jRadioButton2.setSelected(false);
                } catch (Exception e) {
                        System.out.println(e);
                        return;
                }

        }// GEN-LAST:event_insertbtnActionPerformed

        private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updatebtnActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_updatebtnActionPerformed

        private void DateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DateActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_DateActionPerformed

        private void HourActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HourActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_HourActionPerformed

        private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jRadioButton1ActionPerformed

        private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton2ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jRadioButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Hour;
    private javax.swing.JTextField Minute;
    private javax.swing.JTextField Month;
    private javax.swing.JTextField Year;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField clientID;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField employeeID;
    private javax.swing.JLabel fnamelabel;
    private javax.swing.JButton insertbtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lnamelabel;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JButton selectClient;
    private javax.swing.JButton selectEmployee;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
