/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DecorateMyNest;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ponki
 */
public class ClientView extends javax.swing.JFrame {

    /**
     * Creates new form adiminview
     */
    DefaultTableModel model = new DefaultTableModel();

    public ClientView() {
        initComponents();
        setRecordsToTable();
    }

    private void setRecordsToTable() {
        try {
            Welcome.jdbc.preparedStatement = Welcome.jdbc.connection
                    .prepareStatement("SELECT * FROM Clients;");
            Welcome.jdbc.resultSet = Welcome.jdbc.preparedStatement.executeQuery();
            model = (DefaultTableModel) clienttable.getModel();
            while (Welcome.jdbc.resultSet.next()) {
                int clientId = Welcome.jdbc.resultSet.getInt("ClientID");
                String fName = Welcome.jdbc.resultSet.getString("FirstName");
                String lName = Welcome.jdbc.resultSet.getString("LastName");
                String email = Welcome.jdbc.resultSet.getString("Email");
                String phone = Welcome.jdbc.resultSet.getString("Phone");
                String address = Welcome.jdbc.resultSet.getString("Address");
                model.addRow(new Object[] { clientId, fName, lName, email, phone, address });
            }
            clienttable.setModel(model);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editbtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();
        clientsbtn = new javax.swing.JButton();
        clientsbtn1 = new javax.swing.JButton();
        EmployeeRosterbtn = new javax.swing.JButton();
        Vendorsbtn = new javax.swing.JButton();
        Cataloguebtn = new javax.swing.JButton();
        Appointmentsbtn = new javax.swing.JButton();
        Reservationbtn = new javax.swing.JButton();
        FinancialTransactionsbtn = new javax.swing.JButton();
        Inprogressbtn = new javax.swing.JButton();
        MaterialInventorybtn = new javax.swing.JButton();
        ProjectArchivebtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxselectcolumn = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        okbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clienttable = new javax.swing.JTable();
        searchbylabel = new javax.swing.JLabel();
        dltbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(171, 119, 192));

        editbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        viewbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        clientsbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clientsbtn.setText("Admin");
        clientsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsbtnActionPerformed(evt);
            }
        });

        clientsbtn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clientsbtn1.setText("Clients");
        clientsbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsbtn1ActionPerformed(evt);
            }
        });

        EmployeeRosterbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmployeeRosterbtn.setText("EmployeeRoster");
        EmployeeRosterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeRosterbtnActionPerformed(evt);
            }
        });

        Vendorsbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Vendorsbtn.setText("Vendors");
        Vendorsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendorsbtnActionPerformed(evt);
            }
        });

        Cataloguebtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cataloguebtn.setText("Catalogue");
        Cataloguebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CataloguebtnActionPerformed(evt);
            }
        });

        Appointmentsbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Appointmentsbtn.setText("Appointments");
        Appointmentsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentsbtnActionPerformed(evt);
            }
        });

        Reservationbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Reservationbtn.setText("Reservation");
        Reservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationbtnActionPerformed(evt);
            }
        });

        FinancialTransactionsbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FinancialTransactionsbtn.setText("Financial Transactions");
        FinancialTransactionsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinancialTransactionsbtnActionPerformed(evt);
            }
        });

        Inprogressbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Inprogressbtn.setText("Inprogression");
        Inprogressbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InprogressbtnActionPerformed(evt);
            }
        });

        MaterialInventorybtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MaterialInventorybtn.setText("Material Inventory");
        MaterialInventorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaterialInventorybtnActionPerformed(evt);
            }
        });

        ProjectArchivebtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProjectArchivebtn.setText("Project Archive");
        ProjectArchivebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectArchivebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(EmployeeRosterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Vendorsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Cataloguebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Appointmentsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Reservationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FinancialTransactionsbtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Inprogressbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MaterialInventorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ProjectArchivebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clientsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(clientsbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(42, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32,
                                        Short.MAX_VALUE)
                                .addComponent(clientsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31,
                                        Short.MAX_VALUE)
                                .addComponent(clientsbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(EmployeeRosterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Vendorsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Cataloguebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Appointmentsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Reservationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(FinancialTransactionsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Inprogressbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(MaterialInventorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(ProjectArchivebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jComboBoxselectcolumn.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        okbtn.setBackground(new java.awt.Color(153, 255, 153));
        okbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        okbtn.setText("OK");

        clienttable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "ClientID", "FirstName", "LastName", "Email", "Phone", "Address"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(clienttable);

        searchbylabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchbylabel.setText("Search By");

        dltbtn.setBackground(new java.awt.Color(153, 255, 153));
        dltbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dltbtn.setText("Delete");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(searchbylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(okbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jComboBoxselectcolumn,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 236,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 303,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 886,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(424, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dltbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxselectcolumn, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchbylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(okbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dltbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        ClientEdit clientEdit = new ClientEdit();
        clientEdit.show();
        dispose();
    }// GEN-LAST:event_editbtnActionPerformed

    private void FinancialTransactionsbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FinancialTransactionsbtnActionPerformed
        // TODO add your handling code here:
        FinancialTransactionView financialTransactionView = new FinancialTransactionView();
        financialTransactionView.show();
        dispose();
    }// GEN-LAST:event_FinancialTransactionsbtnActionPerformed

    private void InprogressbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_InprogressbtnActionPerformed
        // TODO add your handling code here:
        InprogressionView inprogressionView = new InprogressionView();
        inprogressionView.show();
        dispose();
    }// GEN-LAST:event_InprogressbtnActionPerformed

    private void MaterialInventorybtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MaterialInventorybtnActionPerformed
        // TODO add your handling code here:
        MaterialInventoryView materialInventoryView = new MaterialInventoryView();
        materialInventoryView.show();
        dispose();
    }// GEN-LAST:event_MaterialInventorybtnActionPerformed

    private void ProjectArchivebtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ProjectArchivebtnActionPerformed
        // TODO add your handling code here:
        ProjectArchiveView projectArchiveView = new ProjectArchiveView();
        projectArchiveView.show();
        dispose();
    }// GEN-LAST:event_ProjectArchivebtnActionPerformed

    private void clientsbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clientsbtnActionPerformed
        // TODO add your handling code here:
        ClientView adminView = new ClientView();
        adminView.show();
        dispose();
    }// GEN-LAST:event_clientsbtnActionPerformed

    private void clientsbtn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clientsbtn1ActionPerformed
        // TODO add your handling code here:
        ClientView clientView = new ClientView();
        clientView.show();
        dispose();
    }// GEN-LAST:event_clientsbtn1ActionPerformed

    private void EmployeeRosterbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EmployeeRosterbtnActionPerformed
        // TODO add your handling code here:
        EmployeeRosterView employeeRosterView = new EmployeeRosterView();
        employeeRosterView.show();
        dispose();
    }// GEN-LAST:event_EmployeeRosterbtnActionPerformed

    private void VendorsbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VendorsbtnActionPerformed
        // TODO add your handling code here:
        VendorsView vendorsView = new VendorsView();
        vendorsView.show();
        dispose();
    }// GEN-LAST:event_VendorsbtnActionPerformed

    private void CataloguebtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CataloguebtnActionPerformed
        // TODO add your handling code here:
        CatalogueView catalogueView = new CatalogueView();
        catalogueView.show();
        dispose();
    }// GEN-LAST:event_CataloguebtnActionPerformed

    private void AppointmentsbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AppointmentsbtnActionPerformed
        // TODO add your handling code here:
        ClientView appointmentsView = new ClientView();
        appointmentsView.show();
        dispose();
    }// GEN-LAST:event_AppointmentsbtnActionPerformed

    private void ReservationbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ReservationbtnActionPerformed
        // TODO add your handling code here:
        ReservationView reservationView = new ReservationView();
        reservationView.show();
        dispose();
    }// GEN-LAST:event_ReservationbtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
        ClientView adminView = new ClientView();
        adminView.show();
        dispose();
    }// GEN-LAST:event_viewbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Appointmentsbtn;
    private javax.swing.JButton Cataloguebtn;
    private javax.swing.JButton EmployeeRosterbtn;
    private javax.swing.JButton FinancialTransactionsbtn;
    private javax.swing.JButton Inprogressbtn;
    private javax.swing.JButton MaterialInventorybtn;
    private javax.swing.JButton ProjectArchivebtn;
    private javax.swing.JButton Reservationbtn;
    private javax.swing.JButton Vendorsbtn;
    private javax.swing.JButton clientsbtn;
    private javax.swing.JButton clientsbtn1;
    private javax.swing.JTable clienttable;
    private javax.swing.JButton dltbtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JComboBox<String> jComboBoxselectcolumn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton okbtn;
    private javax.swing.JLabel searchbylabel;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables

}
