/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DecorateMyNest;

import javax.swing.JOptionPane;

/**
 *
 * @author Musaddique Ali
 */
public class EmployeeRosterEditPanel extends javax.swing.JPanel {

        /**
         * Creates new form AdminViewPanel
         */
        public EmployeeRosterEditPanel() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                fnamelabel = new javax.swing.JLabel();
                fName = new javax.swing.JTextField();
                lnamelabel = new javax.swing.JLabel();
                lName = new javax.swing.JTextField();
                email = new javax.swing.JTextField();
                emaillabel = new javax.swing.JLabel();
                phonelabel = new javax.swing.JLabel();
                phone = new javax.swing.JTextField();
                addresslabel = new javax.swing.JLabel();
                position = new javax.swing.JTextField();
                insertbtn = new javax.swing.JButton();
                updatebtn = new javax.swing.JButton();
                clearbtn = new javax.swing.JButton();
                addresslabel1 = new javax.swing.JLabel();
                adminID = new javax.swing.JTextField();

                fnamelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                fnamelabel.setText("First Name");

                lnamelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lnamelabel.setText("Last Name");

                emaillabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                emaillabel.setText("Email");

                phonelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                phonelabel.setText("Phone");

                addresslabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                addresslabel.setText("Position");

                insertbtn.setBackground(new java.awt.Color(243, 239, 13));
                insertbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                insertbtn.setText("Insert");
                insertbtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                insertbtnActionPerformed(evt);
                        }
                });

                updatebtn.setBackground(new java.awt.Color(243, 239, 13));
                updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                updatebtn.setText("Update");

                clearbtn.setBackground(new java.awt.Color(243, 239, 13));
                clearbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                clearbtn.setText("Clear");
                clearbtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearbtnActionPerformed(evt);
                        }
                });

                addresslabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                addresslabel1.setText("Admin ID");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(69, 69, 69)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(fnamelabel,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(lnamelabel,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                177,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(emaillabel,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                177,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(phonelabel,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                177,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(addresslabel,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                177,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(addresslabel1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                177,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(fName,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                441,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(lName,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                441,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(email,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                441,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(phone,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                441,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(position,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                441,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(adminID,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                441,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(insertbtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                115,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(42, 42, 42)
                                                                                                .addComponent(updatebtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                122,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(39, 39, 39)
                                                                                                .addComponent(clearbtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                123,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(937, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(198, 198, 198)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(fnamelabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(fName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(33, 33, 33)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lnamelabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(33, 33, 33)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(emaillabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(email,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(33, 33, 33)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(phonelabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(phone,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(33, 33, 33)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(addresslabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(position,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(33, 33, 33)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(addresslabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(adminID,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                55,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(69, 69, 69)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(insertbtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                48,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(updatebtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                48,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(clearbtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                48,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
        }// </editor-fold>//GEN-END:initComponents

        private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_insertbtnActionPerformed
                if (fName.getText().equals("") || lName.getText().equals("") || email.getText().equals("")
                                || phone.getText().equals("") || position.getText().equals("")
                                || adminID.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Please Fill-up all fields");
                        return;
                }
                try {
                        Welcome.jdbc.EmployeeInsert(fName.getText(), lName.getText(), email.getText(), phone.getText(),
                                        position.getText(), Integer.parseInt(adminID.getText()));
                        JOptionPane.showMessageDialog(this, "Inserted Successfully");
                        fName.setText("");
                        lName.setText("");
                        email.setText("");
                        phone.setText("");
                        position.setText("");
                        adminID.setText("");

                } catch (Exception e) {
                        System.out.println(e);
                        return;
                }
        }// GEN-LAST:event_insertbtnActionPerformed

        private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearbtnActionPerformed
                // TODO add your handling code here:
                fName.setText("");
                lName.setText("");
                email.setText("");
                phone.setText("");
                position.setText("");
                adminID.setText("");
        }// GEN-LAST:event_clearbtnActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel addresslabel;
        private javax.swing.JLabel addresslabel1;
        private javax.swing.JTextField adminID;
        private javax.swing.JButton clearbtn;
        private javax.swing.JTextField email;
        private javax.swing.JLabel emaillabel;
        private javax.swing.JTextField fName;
        private javax.swing.JLabel fnamelabel;
        private javax.swing.JButton insertbtn;
        private javax.swing.JTextField lName;
        private javax.swing.JLabel lnamelabel;
        private javax.swing.JTextField phone;
        private javax.swing.JLabel phonelabel;
        private javax.swing.JTextField position;
        private javax.swing.JButton updatebtn;
        // End of variables declaration//GEN-END:variables
}
