/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DecorateMyNest;

/**
 *
 * @author Musaddique Ali
 */
public class FinancialTransactionEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminViewPanel
     */
    public FinancialTransactionEditPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fnamelabel = new javax.swing.JLabel();
        firstnametxtfield = new javax.swing.JTextField();
        lnamelabel = new javax.swing.JLabel();
        lastnametxtfield = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        emaillabel = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        addresslabel = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        insertbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        deletebtn2 = new javax.swing.JButton();
        deletebtn3 = new javax.swing.JButton();

        fnamelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fnamelabel.setText("First Name");

        lnamelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lnamelabel.setText("Lastr Name");

        emaillabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emaillabel.setText("Email");

        phonelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phonelabel.setText("Phone");

        addresslabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addresslabel.setText("Address");

        insertbtn.setBackground(new java.awt.Color(163, 239, 89));
        insertbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        insertbtn.setText("MaterialTransaction");
        insertbtn.setBorder(null);
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(163, 239, 89));
        deletebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deletebtn.setText("SalaryTransaction");
        deletebtn.setBorder(null);
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        deletebtn2.setBackground(new java.awt.Color(163, 239, 89));
        deletebtn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deletebtn2.setText("InstallmentTransaction");
        deletebtn2.setBorder(null);
        deletebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtn2ActionPerformed(evt);
            }
        });

        deletebtn3.setBackground(new java.awt.Color(163, 239, 89));
        deletebtn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deletebtn3.setText("ReservationTransaction");
        deletebtn3.setBorder(null);
        deletebtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(fnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                177, Short.MAX_VALUE)
                                                        .addComponent(emaillabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                177, Short.MAX_VALUE)
                                                        .addComponent(phonelabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                177, Short.MAX_VALUE)
                                                        .addComponent(addresslabel,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 177,
                                                                Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(firstnametxtfield,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 441,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lastnametxtfield,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 441,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(addresstxt,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 441,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(deletebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 206,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(deletebtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 227,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 179,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 209,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(652, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deletebtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deletebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firstnametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastnametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(phonelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_insertbtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_insertbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_deletebtnActionPerformed

    private void deletebtn2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deletebtn2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_deletebtn2ActionPerformed

    private void deletebtn3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deletebtn3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_deletebtn3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslabel;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton deletebtn2;
    private javax.swing.JButton deletebtn3;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField firstnametxtfield;
    private javax.swing.JLabel fnamelabel;
    private javax.swing.JButton insertbtn;
    private javax.swing.JTextField lastnametxtfield;
    private javax.swing.JLabel lnamelabel;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JTextField phonetxt;
    // End of variables declaration//GEN-END:variables
}
