/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DecorateMyNest;

import java.awt.Dialog;
import java.sql.Date;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Musaddique Ali
 */
public class ReservationTransEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminViewPanel
     */
    public ReservationTransEditPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        insertbtn1 = new javax.swing.JButton();
        addresslabel1 = new javax.swing.JLabel();
        reservationID = new javax.swing.JTextField();
        lnamelabel = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        emaillabel = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        fnamelabel = new javax.swing.JLabel();
        adminID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        Year = new javax.swing.JTextField();
        Month = new javax.swing.JTextField();
        selectAdmin = new javax.swing.JButton();
        selectReservation = new javax.swing.JButton();

        updatebtn.setBackground(new java.awt.Color(243, 239, 13));
        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updatebtn.setText("Update");

        clearbtn.setBackground(new java.awt.Color(243, 239, 13));
        clearbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        insertbtn1.setBackground(new java.awt.Color(243, 239, 13));
        insertbtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        insertbtn1.setText("Insert");
        insertbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtn1ActionPerformed(evt);
            }
        });

        addresslabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addresslabel1.setText("Reservation ID");

        lnamelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lnamelabel.setText("Transaction Date");

        emaillabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emaillabel.setText("Amount");

        phonelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phonelabel.setText("Description");

        fnamelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fnamelabel.setText("AdminID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setText("/");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setText("/");

        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        selectAdmin.setText("Select");
        selectAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAdminActionPerformed(evt);
            }
        });

        selectReservation.setText("Select");
        selectReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectReservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(insertbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addresslabel1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 177,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(fnamelabel,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(lnamelabel,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(emaillabel,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(phonelabel,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 145,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(adminID,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 441,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(selectAdmin,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 106,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(description,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 441,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(reservationID,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 441,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(selectReservation,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 106,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Date,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 103,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Month,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 103,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Year,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 103,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(813, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminID, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selectAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(phonelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addresslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(reservationID, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selectReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(insertbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(172, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void selectAdminActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectAdminActionPerformed
        // TODO add your handling code here:
        JDialog selectDialog = new JDialog(new JFrame(), "Select Admin ID", Dialog.ModalityType.APPLICATION_MODAL);
        selectDialog.add(new SelectAdmin());
        selectDialog.setSize(1230, 850);
        selectDialog.setVisible(true);
        adminID.setText(Welcome.jdbc.adminID + "");
        Welcome.jdbc.adminID = -1;
    }// GEN-LAST:event_selectAdminActionPerformed

    private void selectReservationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectReservationActionPerformed
        // TODO add your handling code here:
        JDialog selectDialog = new JDialog(new JFrame(), "Select Reservation ID",
                Dialog.ModalityType.APPLICATION_MODAL);
        selectDialog.add(new SelectReservation());
        selectDialog.setSize(1230, 850);
        selectDialog.setVisible(true);
        reservationID.setText(Welcome.jdbc.reservationID + "");
        Welcome.jdbc.reservationID = -1;
    }// GEN-LAST:event_selectReservationActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        adminID.setText("");
        Date.setText("");
        Month.setText("");
        Year.setText("");
        amount.setText("");
        description.setText("");
        reservationID.setText("");
    }// GEN-LAST:event_clearbtnActionPerformed

    private void insertbtn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_insertbtn1ActionPerformed
        if (adminID.getText().equals("") || Date.getText().equals("") || Month.getText().equals("")
                || Year.getText().equals("") || amount.getText().equals("")
                || description.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fill-up all fields");
            return;
        }
        try {
            Welcome.jdbc.financialTransInsert(Integer.parseInt(adminID.getText()),
                    new Date(Integer.parseInt(Year.getText()) - 1900, Integer.parseInt(Month.getText()) - 1,
                            Integer.parseInt(Date.getText())),
                    Double.parseDouble(amount.getText()), description.getText());
        } catch (Exception e) {
            System.out.println(e);
            return;
        }

        if (reservationID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fill-up all fields");
            return;
        }
        try {
            int highestTransactionID = Welcome.jdbc.getHighestTransactionID();

            Welcome.jdbc.reservationTransactionInsert(highestTransactionID,
                    Integer.parseInt(reservationID.getText()));
            JOptionPane.showMessageDialog(this, "Inserted Successfully");
            // Clear your input fields related to ReservationTransaction here
            adminID.setText("");
            Date.setText("");
            Month.setText("");
            Year.setText("");
            amount.setText("");
            description.setText("");
            reservationID.setText("");
        } catch (Exception e) {
            System.out.println(e);
            return;
        }

    }// GEN-LAST:event_insertbtn1ActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_DateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Month;
    private javax.swing.JTextField Year;
    private javax.swing.JLabel addresslabel1;
    private javax.swing.JTextField adminID;
    private javax.swing.JTextField amount;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField description;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JLabel fnamelabel;
    private javax.swing.JButton insertbtn1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lnamelabel;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JTextField reservationID;
    private javax.swing.JButton selectAdmin;
    private javax.swing.JButton selectReservation;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
