/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DecorateMyNest;

/**
 *
 * @author Musaddique Ali
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    public ViewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Adminbtn = new javax.swing.JButton();
        Clientsbtn = new javax.swing.JButton();
        EmployeeRosterbtn = new javax.swing.JButton();
        Vendorsbtn = new javax.swing.JButton();
        Cataloguebtn = new javax.swing.JButton();
        Appointmentsbtn = new javax.swing.JButton();
        Reservationbtn = new javax.swing.JButton();
        FinancialTransactionsbtn = new javax.swing.JButton();
        Inprogressbtn = new javax.swing.JButton();
        MaterialInventorybtn = new javax.swing.JButton();
        ProjectArchivebtn = new javax.swing.JButton();

        Adminbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Adminbtn.setText("Admin");
        Adminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminbtnActionPerformed(evt);
            }
        });

        Clientsbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Clientsbtn.setText("Clients");
        Clientsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientsbtnActionPerformed(evt);
            }
        });

        EmployeeRosterbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        EmployeeRosterbtn.setText("EmployeeRoster");
        EmployeeRosterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeRosterbtnActionPerformed(evt);
            }
        });

        Vendorsbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Vendorsbtn.setText("Vendors");
        Vendorsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendorsbtnActionPerformed(evt);
            }
        });

        Cataloguebtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Cataloguebtn.setText("Catalogue");
        Cataloguebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CataloguebtnActionPerformed(evt);
            }
        });

        Appointmentsbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Appointmentsbtn.setText("Appointments");
        Appointmentsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentsbtnActionPerformed(evt);
            }
        });

        Reservationbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Reservationbtn.setText("Reservation");
        Reservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationbtnActionPerformed(evt);
            }
        });

        FinancialTransactionsbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        FinancialTransactionsbtn.setText("Financial Transactions");
        FinancialTransactionsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinancialTransactionsbtnActionPerformed(evt);
            }
        });

        Inprogressbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Inprogressbtn.setText("Inprogression");
        Inprogressbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InprogressbtnActionPerformed(evt);
            }
        });

        MaterialInventorybtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MaterialInventorybtn.setText("Material Inventory");
        MaterialInventorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaterialInventorybtnActionPerformed(evt);
            }
        });

        ProjectArchivebtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ProjectArchivebtn.setText("Project Archive");
        ProjectArchivebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectArchivebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inprogressbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeRosterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vendorsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cataloguebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Appointmentsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reservationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FinancialTransactionsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaterialInventorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjectArchivebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clientsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(Adminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Clientsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmployeeRosterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Vendorsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cataloguebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Appointmentsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Reservationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FinancialTransactionsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Inprogressbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MaterialInventorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProjectArchivebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AdminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminbtnActionPerformed

    private void ClientsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientsbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientsbtnActionPerformed

    private void EmployeeRosterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeRosterbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeRosterbtnActionPerformed

    private void VendorsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendorsbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VendorsbtnActionPerformed

    private void CataloguebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CataloguebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CataloguebtnActionPerformed

    private void AppointmentsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentsbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppointmentsbtnActionPerformed

    private void ReservationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservationbtnActionPerformed

    private void FinancialTransactionsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinancialTransactionsbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinancialTransactionsbtnActionPerformed

    private void InprogressbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InprogressbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InprogressbtnActionPerformed

    private void MaterialInventorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaterialInventorybtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialInventorybtnActionPerformed

    private void ProjectArchivebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectArchivebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProjectArchivebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adminbtn;
    private javax.swing.JButton Appointmentsbtn;
    private javax.swing.JButton Cataloguebtn;
    private javax.swing.JButton Clientsbtn;
    private javax.swing.JButton EmployeeRosterbtn;
    private javax.swing.JButton FinancialTransactionsbtn;
    private javax.swing.JButton Inprogressbtn;
    private javax.swing.JButton MaterialInventorybtn;
    private javax.swing.JButton ProjectArchivebtn;
    private javax.swing.JButton Reservationbtn;
    private javax.swing.JButton Vendorsbtn;
    // End of variables declaration//GEN-END:variables
}
